version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: dmira-db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    image: dmira-core-image
    container_name: dmira-core
    ports:
      - 8080:8080
    links:
      - mongodb