version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: dimra_db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  db-client:
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    depends_on:
      - db

  app:
    build: .
    image: dmira-core-image
    container_name: dmira-core-image
    ports:
      - 8080:8080
    depends_on:
      - db